import type { Metadata } from "next";
import PageLayout from "@/app/utils/PageLayout";
import { IBM_Plex_Sans_Thai } from "next/font/google";
import { CustomProviders } from "./provider";
import "./globals.css";

const IBM = IBM_Plex_Sans_Thai({
  subsets: ["latin", "thai"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "MOC | Khon Kaen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CustomProviders>
      <html lang="en">
        <body className={`${IBM.className} antialiased`}>
          <PageLayout>{children}</PageLayout>
        </body>
      </html>
    </CustomProviders>
  );
}
